### GET all adresses
GET http://localhost:8080/adresses

### GET adresse by id
GET http://localhost:8080/adresses/1

### POST create new adresse
POST http://localhost:8080/adresses
Content-Type: application/json

{
  "adresseBase": "111 Rue de la République",
  "complement": "Appartement 5",
  "codePostal": "75001",
  "ville": "Paris"
}

### PUT update adresse by id
PUT http://localhost:8080/adresses/1
Content-Type: application/json

{
  "id": 1,
  "adresseBase": "222 Boulevard Gustave Flaubert",
  "complement": "Le Sextant",
  "codePostal": "63000",
  "ville": "Clermont-Ferrand"
}

### DELETE adresse by id
DELETE http://localhost:8080/adresses/1