### GET all utilisateurs
GET http://localhost:8080/utilisateurs

### GET utilisateur by id
GET http://localhost:8080/utilisateurs/1

### POST create new utilisateur
POST http://localhost:8080/utilisateurs
Content-Type: application/json

{
  "nom": "Dupont",
  "prenom": "Jean",
  "email": "jean.dupont@example.com",
  "dateNaissance": "1980-01-01",
  "motDePasse": "P@ssw0rd",
  "telephone": "0123456789",
  "adresse": {
    "adresseBase": "111 Rue de la République",
    "complement": "Appartement 5",
    "codePostal": "75001",
    "ville": "Paris"
  },
  "role": "UTILISATEUR"
}

### PUT update utilisateur by id
PUT http://localhost:8080/utilisateurs/1
Content-Type: application/json

{
  "id": 1,
  "motDePasse": "P@ssw0rdSup3rAdm1n",
  "role": "ADMINISTRATEUR"
}

### DELETE utilisateur by id
DELETE http://localhost:8080/utilisateurs/1