spring.application.name=api

server.port=3000

spring.datasource.url=jdbc:mysql://localhost:3306/electricity_business?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=electricitybusiness
spring.datasource.password=electricitybusiness

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=a23ac96ce968bf13099d99410b951dd498118851bdfc996a3f844bd68b1b2afd